on:
  branch_protection_rule:
  push:
    branches:
      - main
  schedule:
    - cron: "42 4 * * MON"

permissions: {}

jobs:
  scorecard:
    permissions:
      contents: read
      id-token: write # for result authenticity verification when publishing on scorecard.dev
      security-events: write # for issuing code scanning findings in the GitHub project
    uses: ./.github/workflows/openssf-scorecard.yaml
    with:
      publish-results: true
